name: Build Debug APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Gradle build (assembleDebug)
        run: ./gradlew assembleDebug
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: SnapTendance-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
